import BaseLayout from '@/components/BaseLayout/BaseLayout'
import './globals.css'
import StyledComponentsRegistry from './stylesheet'

export const metadata = {
  title: 'Myline',
  description: 'Generated by create next app',
}

export default function RootLayout(ctx) {
  console.log(ctx.params)
  return (
    <html lang="ru">
      <body>
        <StyledComponentsRegistry>
          <BaseLayout>
            {ctx.children}
          </BaseLayout>
        </StyledComponentsRegistry>
        </body>
    </html>
  )
}
