export const metadata = {
  title: 'Каталог',
  description: 'Generated by create next app',
}

export default function Layout(ctx) {
  console.log(ctx.params)
  return (
    <>
      {ctx.children}  
    </>    
  )
}